apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
data:
  SLACK_CHANNEL: {{ .Values.config.slackChannel | quote }}
  CHECK_INTERVAL: {{ .Values.config.interval | quote }}
  FILTERS: {{ .Values.config.filters | quote }}
  COUNTRY: {{ .Values.config.country | quote }}
  PROCESS_INIT: {{ .Values.config.processInit | quote }}